[package]
name = "husky-glacier-linux"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "huskyglacier"
path = "src/main.rs"

[dependencies]
hidapi = "2.6.5"
log = "0.4"
regex = "1"
systemd-journal-logger = "2"
